---
- name: Deploy Scientific Calculator Container
  hosts: all
  become: yes
  become_method: sudo  # Ensures Ansible uses sudo properly

  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image from Docker Hub
      command: docker pull pgp2024019/scientific-calculator:latest

    - name: Stop and Remove Existing Container (if any)
      command: docker rm -f Calculator
      ignore_errors: yes

    - name: Run the Container
      command: >
        docker run -d --name Calculator
        -p 5000:5000 pgp2024019/scientific-calculator:latest
